package com.github.tomschi.commons.data.dbo.sql;

/**
 * The interface {@link SQLSequenceDbo} is the base interface for
 * all SQL based database objects, where the id is generated by a
 * database sequence. The id is of type {@link Long}.
 *
 * @author Tomschi
 * @since 0.1.0
 */
public interface SQLSequenceDbo extends SQLDatabaseObject<Long> {
}
