language: java
sudo: false

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

after_success:
  - mvn clean cobertura:cobertura coveralls:report

deploy:
  provider: bintray
  file: bintray.json
  user: tomschi
  key:
  dry-run: true