language: java
sudo: false
jdk:
- oraclejdk8

after_success:
- mvn clean cobertura:cobertura coveralls:report

before_deploy:
- mvn clean package -DskipTests

deploy:
  - provider: bintray
    file: bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x

  - provider: bintray
    file: commons-annotation/target/deploy-descriptors/bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x

  - provider: bintray
    file: commons-aspect/target/deploy-descriptors/bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x

  - provider: bintray
    file: commons-data/target/deploy-descriptors/bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x

  - provider: bintray
    file: commons-slf4j/target/deploy-descriptors/bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x

  - provider: bintray
    file: commons-spring-data/target/deploy-descriptors/bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x

  - provider: bintray
    file: commons-spring-data-jpa/target/deploy-descriptors/bintray.json
    user: tomschi
    key:
      secure: FHsNg3SLwTy0yxICgodMzUSA7Jus8zXvnmOAc+iPnLnuLr7WCt4M3tWfuIhFdmgsbltr6h060U//kmKW9JTOEOG126OGZk9TTlftTNjYvPrHwIpRUBPvxVBolF8m99zohXM5giQzcdjCfXCaRiOAyow4FL01paPOSiTKx6nOakV46dNNeBgzyuyXSp9nmRLGG3EQWAJtepXKWXxDIeShplf1IArloFxOgOLkD+fW84xYo9GKvHW2QMVTFgJKBbC9nCDNgthinxPwoIGFg6l81g0LffAl4hNvAMrHnvukyKRPzs2o8DQ+f6x5Bu76NGmvbu0E9NChComl3k0RvnpuiwdU2FXt/HD6/I1cs70u57qULj++ktyMmoVLaF3KCqNYqjJkz01+4Q3N5ooLD0xJ7b46ECm9kcr0zAaYKPKDfPig+7Xd0q5i1x7/lA6ddxSsOeLR6a+we35wTCK0CghHRvs2/CFviV05bp/i7oXcfwHdJwRmanwKMQJexgnrdfOkr2/FbKMQCcsoDzq0K/P+akAD6nuRiMCX/RHK4EeoFlpUDuuLTWoeNnjSpSkV0AEzfQLXssk70Mnj6IktmK6LSRsoR7J4muterIqlQOPgPKHr6CMoenUY1DUFBpfqSKmci9krGIuSwMmO2euh/COTo7weakapthWXQL6EeomROPY=
    dry-run: false
    skip_cleanup: true
    on: v0.2.x